# Use an official Python runtime as a parent image
FROM python:3.9-slim

# Set the working directory in the container
WORKDIR /app

# Install system dependencies
RUN apt-get update && \
    apt-get install -y git && \
    rm -rf /var/lib/apt/lists/*

# Copy the requirements file into the container
COPY requirements.txt .

# Install Python dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Download NLTK data
RUN python -m nltk.downloader punkt -d /usr/local/nltk_data

# Set the NLTK_DATA environment variable
ENV NLTK_DATA=/usr/local/nltk_data

# Copy the rest of the application code
COPY . .

# Expose the port that Streamlit runs on
EXPOSE 8501

# Download and cache models during build
RUN python -c "from transformers import RobertaTokenizer, RobertaForSequenceClassification; \
RobertaTokenizer.from_pretrained('SamLowe/roberta-base-go_emotions'); \
RobertaForSequenceClassification.from_pretrained('SamLowe/roberta-base-go_emotions')"

# Command to run the application
ENTRYPOINT ["streamlit", "run", "app.py", "--server.port=8501", "--server.address=0.0.0.0"]
